using System.Text.Json;
using System.Text.Json.Nodes;
using Lorex.Core.Adapters;
using Lorex.Core.Models;
using Lorex.Core.Serialization;

namespace Lorex.Core.Services;

/// <summary>
/// Projects lorex artifacts into each configured agent's native integration surface.
/// </summary>
public sealed class AdapterService
{
    private const string LegacyStartMarker = "<!-- lorex:start -->";
    private const string LegacyEndMarker = "<!-- lorex:end -->";
    private const string GeneratedMarkdownMarker = "<!-- Generated by lorex -->";
    private const string GeneratedTomlMarker = "# Generated by lorex";

    public static readonly IReadOnlyDictionary<string, IAdapter> KnownAdapters =
        new Dictionary<string, IAdapter>(StringComparer.OrdinalIgnoreCase)
        {
            ["copilot"] = new CopilotAdapter(),
            ["codex"] = new CodexAdapter(),
            ["cursor"] = new CursorAdapter(),
            ["claude"] = new ClaudeAdapter(),
            ["windsurf"] = new WindsurfAdapter(),
            ["cline"] = new ClineAdapter(),
            ["roo"] = new RooAdapter(),
            ["gemini"] = new GeminiAdapter(),
            ["opencode"] = new OpenCodeAdapter(),
        };

    public void Project(string projectRoot, LorexConfig config, ArtifactKind? kindFilter = null)
    {
        CleanupLegacyFiles(projectRoot);

        foreach (var adapterName in config.Adapters)
        {
            if (!KnownAdapters.TryGetValue(adapterName, out var adapter))
                continue;

            ProjectAdapter(projectRoot, config, adapter, kindFilter);
        }
    }

    public void ProjectTarget(string projectRoot, LorexConfig config, string adapterName, ArtifactKind? kindFilter = null)
    {
        if (!KnownAdapters.TryGetValue(adapterName, out var adapter))
            throw new ArgumentException($"Unknown adapter '{adapterName}'. Known adapters: {string.Join(", ", KnownAdapters.Keys)}");

        CleanupLegacyFiles(projectRoot);
        ProjectAdapter(projectRoot, config, adapter, kindFilter);
    }

    public IReadOnlyList<AdapterTargetDescription> DescribeTargets(string projectRoot, string adapterName, ArtifactKind? kindFilter = null)
    {
        if (!KnownAdapters.TryGetValue(adapterName, out var adapter))
            throw new ArgumentException($"Unknown adapter '{adapterName}'. Known adapters: {string.Join(", ", KnownAdapters.Keys)}");

        var kinds = kindFilter is null
            ? new[] { ArtifactKind.Skill, ArtifactKind.Prompt }
            : new[] { kindFilter.Value };

        var targets = new List<AdapterTargetDescription>();
        foreach (var kind in kinds)
        {
            var projection = adapter.GetProjection(projectRoot, kind);
            if (projection is null)
                continue;

            switch (projection)
            {
                case SkillDirectoryProjection skillRoot:
                    targets.Add(new AdapterTargetDescription(kind, skillRoot.RootPath));
                    break;
                case CursorRulesProjection cursor:
                    targets.Add(new AdapterTargetDescription(kind, cursor.RulesDirectory));
                    break;
                case RooRulesProjection roo:
                    targets.Add(new AdapterTargetDescription(kind, roo.RulesDirectory));
                    break;
                case GeminiContextProjection gemini:
                    targets.Add(new AdapterTargetDescription(kind, gemini.SettingsPath));
                    break;
                case PromptProjection prompt:
                    targets.Add(new AdapterTargetDescription(kind, prompt.RootPath));
                    if (!string.IsNullOrWhiteSpace(prompt.AuxiliaryPath))
                        targets.Add(new AdapterTargetDescription(kind, prompt.AuxiliaryPath!));
                    break;
            }
        }

        return targets;
    }

    internal void CleanupLegacyFiles(string projectRoot)
    {
        foreach (var adapter in KnownAdapters.Values)
        {
            foreach (var path in adapter.LegacyPaths(projectRoot))
                CleanupLegacyFile(path);
        }
    }

    internal static void CleanupLegacyFile(string filePath)
    {
        if (!File.Exists(filePath))
            return;

        var existing = File.ReadAllText(filePath);
        var updated = RemoveLegacyBlock(existing);
        if (string.Equals(existing, updated, StringComparison.Ordinal))
            return;

        if (string.IsNullOrWhiteSpace(updated))
        {
            File.Delete(filePath);
            DeleteParentDirectoryIfEmpty(filePath);
            return;
        }

        File.WriteAllText(filePath, updated.Trim() + "\n");
    }

    internal static string RemoveLegacyBlock(string content)
    {
        var startIdx = content.IndexOf(LegacyStartMarker, StringComparison.Ordinal);
        var endIdx = content.IndexOf(LegacyEndMarker, StringComparison.Ordinal);
        if (startIdx < 0 || endIdx < 0 || endIdx <= startIdx)
            return content;

        return string.Concat(content.AsSpan(0, startIdx), content.AsSpan(endIdx + LegacyEndMarker.Length));
    }

    internal string RenderCursorRule(string projectRoot, string skillName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Skill, skillName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Skill, skillName);
        return
            $"---\n" +
            $"description: \"{EscapeYamlScalar(description)}\"\n" +
            "alwaysApply: false\n" +
            "---\n\n" +
            body +
            "\n";
    }

    internal string RenderRooRule(string projectRoot, string skillName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Skill, skillName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Skill, skillName);
        return
            $"# {skillName}\n\n" +
            $"Use this lorex skill when the task matches: {description}\n\n" +
            body +
            "\n";
    }

    internal string RenderCopilotPrompt(string projectRoot, string promptName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Prompt, promptName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Prompt, promptName);
        return
            "---\n" +
            "agent: 'agent'\n" +
            $"description: '{EscapeSingleQuotedScalar(description)}'\n" +
            "---\n\n" +
            $"{GeneratedMarkdownMarker}\n\n" +
            body +
            "\n";
    }

    internal string RenderMarkdownPrompt(string projectRoot, string promptName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Prompt, promptName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Prompt, promptName);
        return
            "---\n" +
            $"description: \"{EscapeYamlScalar(description)}\"\n" +
            "---\n\n" +
            $"{GeneratedMarkdownMarker}\n\n" +
            body +
            "\n";
    }

    internal string RenderWorkflowPrompt(string projectRoot, string promptName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Prompt, promptName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Prompt, promptName);
        return
            $"{GeneratedMarkdownMarker}\n\n" +
            $"# {promptName}\n\n" +
            $"{description}\n\n" +
            "## Step 1: Execute workflow\n" +
            body +
            "\n";
    }

    internal string RenderGeminiCommand(string projectRoot, string promptName)
    {
        var description = GetArtifactDescription(projectRoot, ArtifactKind.Prompt, promptName);
        var body = GetArtifactBody(projectRoot, ArtifactKind.Prompt, promptName)
            .Replace("\"\"\"", "\\\"\\\"\\\"", StringComparison.Ordinal);
        return
            $"{GeneratedTomlMarker}\n" +
            $"description = \"{EscapeTomlString(description)}\"\n" +
            $"prompt = \"\"\"\n{body}\n\"\"\"\n";
    }

    internal void UpdateGeminiSettings(string projectRoot, LorexConfig config, string settingsPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(settingsPath)!);

        using var existing = ReadJsonDocument(settingsPath);
        var root = existing?.RootElement;
        JsonElement? existingContext = null;
        if (root is { ValueKind: JsonValueKind.Object } rootObject &&
            rootObject.TryGetProperty("context", out var contextElement) &&
            contextElement.ValueKind == JsonValueKind.Object)
        {
            existingContext = contextElement;
        }

        var fileNames = ReadStringValues(existingContext, "fileName", StringComparer.Ordinal);
        fileNames.Add(ArtifactKind.Skill.CanonicalFileName());
        var legacySkillFileName = ArtifactKind.Skill.LegacyFileName();
        if (legacySkillFileName is not null)
            fileNames.Add(legacySkillFileName);

        var includeDirectories = ReadStringValues(existingContext, "includeDirectories", StringComparer.OrdinalIgnoreCase)
            .Where(path => !path.Replace('\\', '/').StartsWith(".lorex/skills/", StringComparison.OrdinalIgnoreCase))
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        foreach (var skillName in config.Artifacts.Skills)
            includeDirectories.Add(Path.Combine(".lorex", "skills", skillName).Replace('\\', '/'));

        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            writer.WriteStartObject();

            if (root is { ValueKind: JsonValueKind.Object } rootElement)
            {
                foreach (var property in rootElement.EnumerateObject())
                {
                    if (property.NameEquals("context"))
                        continue;

                    property.WriteTo(writer);
                }
            }

            writer.WritePropertyName("context");
            writer.WriteStartObject();

            if (existingContext is { ValueKind: JsonValueKind.Object } contextObject)
            {
                foreach (var property in contextObject.EnumerateObject())
                {
                    if (property.NameEquals("fileName") ||
                        property.NameEquals("includeDirectories") ||
                        property.NameEquals("loadFromIncludeDirectories"))
                    {
                        continue;
                    }

                    property.WriteTo(writer);
                }
            }

            WriteStringArray(writer, "fileName", fileNames.OrderBy(name => name, StringComparer.Ordinal));
            WriteStringArray(writer, "includeDirectories", includeDirectories.OrderBy(path => path, StringComparer.Ordinal));
            writer.WriteBoolean("loadFromIncludeDirectories", true);
            writer.WriteEndObject();
            writer.WriteEndObject();
        }

        File.WriteAllText(settingsPath, System.Text.Encoding.UTF8.GetString(stream.ToArray()) + "\n");
    }

    internal void UpdateCopilotPromptSettings(string settingsPath)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(settingsPath)!);

        JsonObject rootObject;
        if (File.Exists(settingsPath))
        {
            try
            {
                rootObject = (JsonNode.Parse(File.ReadAllText(settingsPath)) as JsonObject) ?? new JsonObject();
            }
            catch (JsonException)
            {
                rootObject = new JsonObject();
            }
        }
        else
        {
            rootObject = new JsonObject();
        }

        rootObject["chat.promptFiles"] = true;
        File.WriteAllText(settingsPath, rootObject.ToJsonString(new JsonSerializerOptions { WriteIndented = true }) + "\n");
    }

    internal static bool IsLorexManagedProjection(string directoryPath, string lorexSkillsRoot)
    {
        if (!Directory.Exists(directoryPath))
            return false;

        var target = ResolveDirectoryLinkTarget(directoryPath);
        return target is not null && IsWithin(target, lorexSkillsRoot);
    }

    internal static string GetSymlinkTarget(string projectRoot, string linkPath, string targetPath)
    {
        var fullProjectRoot = Path.GetFullPath(projectRoot)
            .TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var fullLinkPath = Path.GetFullPath(linkPath);
        var fullTargetPath = Path.GetFullPath(targetPath);

        if (IsWithin(fullLinkPath, fullProjectRoot) && IsWithin(fullTargetPath, fullProjectRoot))
        {
            var linkDirectory = Path.GetDirectoryName(fullLinkPath)
                ?? throw new InvalidOperationException($"Cannot determine parent directory for '{linkPath}'.");
            return Path.GetRelativePath(linkDirectory, fullTargetPath);
        }

        return fullTargetPath;
    }

    private void ProjectAdapter(string projectRoot, LorexConfig config, IAdapter adapter, ArtifactKind? kindFilter)
    {
        var kinds = kindFilter is null
            ? new[] { ArtifactKind.Skill, ArtifactKind.Prompt }
            : new[] { kindFilter.Value };

        foreach (var kind in kinds)
        {
            var projection = adapter.GetProjection(projectRoot, kind);
            if (projection is null)
                continue;

            switch (projection)
            {
                case SkillDirectoryProjection skillDirectory:
                    ProjectSkillDirectory(projectRoot, config, skillDirectory.RootPath);
                    break;
                case CursorRulesProjection cursorRules:
                    ProjectCursorRules(projectRoot, config, cursorRules.RulesDirectory);
                    break;
                case RooRulesProjection rooRules:
                    ProjectRooRules(projectRoot, config, rooRules.RulesDirectory);
                    break;
                case GeminiContextProjection geminiContext:
                    UpdateGeminiSettings(projectRoot, config, geminiContext.SettingsPath);
                    break;
                case PromptProjection promptProjection:
                    ProjectPromptProjection(projectRoot, config, promptProjection);
                    break;
            }
        }
    }

    private void ProjectSkillDirectory(string projectRoot, LorexConfig config, string rootPath)
    {
        Directory.CreateDirectory(rootPath);

        var installed = config.Artifacts.Skills.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var lorexSkillsRoot = Path.Combine(projectRoot, ".lorex", "skills");

        foreach (var dir in Directory.EnumerateDirectories(rootPath))
        {
            var name = Path.GetFileName(dir);
            if (!installed.Contains(name) && IsLorexManagedProjection(dir, lorexSkillsRoot))
                Directory.Delete(dir, recursive: true);
        }

        foreach (var skillName in config.Artifacts.Skills)
        {
            var sourceDir = Path.Combine(projectRoot, ".lorex", "skills", skillName);
            if (!Directory.Exists(sourceDir))
                continue;

            var targetDir = Path.Combine(rootPath, skillName);
            EnsureSkillProjection(projectRoot, sourceDir, targetDir, lorexSkillsRoot);
        }
    }

    private void ProjectCursorRules(string projectRoot, LorexConfig config, string rulesDirectory)
    {
        Directory.CreateDirectory(rulesDirectory);
        RemoveProjectedFiles(rulesDirectory, "*.mdc");

        foreach (var skillName in config.Artifacts.Skills)
        {
            var path = Path.Combine(rulesDirectory, $"lorex-{skillName}.mdc");
            File.WriteAllText(path, RenderCursorRule(projectRoot, skillName));
        }
    }

    private void ProjectRooRules(string projectRoot, LorexConfig config, string rulesDirectory)
    {
        Directory.CreateDirectory(rulesDirectory);
        RemoveProjectedFiles(rulesDirectory, "*.md");

        foreach (var skillName in config.Artifacts.Skills)
        {
            var path = Path.Combine(rulesDirectory, $"lorex-{skillName}.md");
            File.WriteAllText(path, RenderRooRule(projectRoot, skillName));
        }
    }

    private void ProjectPromptProjection(string projectRoot, LorexConfig config, PromptProjection projection)
    {
        Directory.CreateDirectory(projection.RootPath);

        var expectedPaths = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var promptName in config.Artifacts.Prompts)
        {
            var path = GetPromptProjectionPath(projection, promptName);
            expectedPaths.Add(Path.GetFullPath(path));

            var content = projection.Style switch
            {
                PromptProjectionStyle.Copilot => RenderCopilotPrompt(projectRoot, promptName),
                PromptProjectionStyle.Claude or PromptProjectionStyle.Cursor or PromptProjectionStyle.Roo or PromptProjectionStyle.OpenCode
                    => RenderMarkdownPrompt(projectRoot, promptName),
                PromptProjectionStyle.Workflow => RenderWorkflowPrompt(projectRoot, promptName),
                PromptProjectionStyle.Gemini => RenderGeminiCommand(projectRoot, promptName),
                _ => throw new ArgumentOutOfRangeException(nameof(projection.Style), projection.Style, null),
            };

            var marker = projection.Style == PromptProjectionStyle.Gemini ? GeneratedTomlMarker : GeneratedMarkdownMarker;
            WriteManagedPromptFile(path, content, marker);
        }

        CleanupManagedPromptFiles(projection, expectedPaths);

        if (projection.Style == PromptProjectionStyle.Copilot && projection.AuxiliaryPath is not null)
            UpdateCopilotPromptSettings(projection.AuxiliaryPath);
    }

    private static string GetPromptProjectionPath(PromptProjection projection, string promptName) => projection.Style switch
    {
        PromptProjectionStyle.Copilot => Path.Combine(projection.RootPath, $"{promptName}.prompt.md"),
        PromptProjectionStyle.Gemini => Path.Combine(projection.RootPath, $"{promptName}.toml"),
        _ => Path.Combine(projection.RootPath, $"{promptName}.md"),
    };

    private static void WriteManagedPromptFile(string path, string content, string marker)
    {
        if (File.Exists(path) && !IsManagedPromptFile(path, marker))
            return;

        File.WriteAllText(path, content);
    }

    private static void CleanupManagedPromptFiles(PromptProjection projection, HashSet<string> expectedPaths)
    {
        var searchPattern = projection.Style switch
        {
            PromptProjectionStyle.Copilot => "*.prompt.md",
            PromptProjectionStyle.Gemini => "*.toml",
            _ => "*.md",
        };

        var marker = projection.Style == PromptProjectionStyle.Gemini ? GeneratedTomlMarker : GeneratedMarkdownMarker;

        foreach (var file in Directory.EnumerateFiles(projection.RootPath, searchPattern))
        {
            if (expectedPaths.Contains(Path.GetFullPath(file)))
                continue;

            if (IsManagedPromptFile(file, marker))
                File.Delete(file);
        }
    }

    private static bool IsManagedPromptFile(string path, string marker) =>
        File.Exists(path) &&
        File.ReadAllText(path).Contains(marker, StringComparison.Ordinal);

    private static void EnsureSkillProjection(string projectRoot, string sourceDir, string targetDir, string lorexSkillsRoot)
    {
        if (ArtifactFileConvention.ResolveEntryPath(ArtifactKind.Skill, sourceDir) is null)
            throw new InvalidOperationException($"Skill directory '{sourceDir}' is missing {ArtifactKind.Skill.CanonicalFileName()}.");

        if (Directory.Exists(targetDir))
        {
            if (!IsLorexManagedProjection(targetDir, lorexSkillsRoot))
                return;

            var currentTarget = ResolveDirectoryLinkTarget(targetDir);
            if (currentTarget is not null && PathsEqual(currentTarget, sourceDir))
                return;

            Directory.Delete(targetDir, recursive: true);
        }

        if (!TryCreateDirectorySymlink(projectRoot, targetDir, sourceDir))
        {
            throw new InvalidOperationException(
                $"Lorex requires symlink support for native skill projections. Failed to create '{targetDir}'.");
        }
    }

    private static bool TryCreateDirectorySymlink(string projectRoot, string linkPath, string targetPath)
    {
        try
        {
            Directory.CreateSymbolicLink(linkPath, GetSymlinkTarget(projectRoot, linkPath, targetPath));
            return true;
        }
        catch (IOException)
        {
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static string? ResolveDirectoryLinkTarget(string directoryPath)
    {
        if (!Directory.Exists(directoryPath))
            return null;

        var info = new DirectoryInfo(directoryPath);
        var target = info.LinkTarget;
        if (target is null)
            return null;

        if (Path.IsPathRooted(target))
            return Path.GetFullPath(target);

        var parent = info.Parent?.FullName
            ?? throw new InvalidOperationException($"Cannot determine parent directory for '{directoryPath}'.");
        return Path.GetFullPath(Path.Combine(parent, target));
    }

    private static void RemoveProjectedFiles(string directory, string searchPattern)
    {
        foreach (var file in Directory.EnumerateFiles(directory, searchPattern))
        {
            if (Path.GetFileName(file).StartsWith("lorex-", StringComparison.OrdinalIgnoreCase))
                File.Delete(file);
        }
    }

    private static JsonDocument? ReadJsonDocument(string path)
    {
        if (!File.Exists(path))
            return null;

        var json = File.ReadAllText(path);
        if (string.IsNullOrWhiteSpace(json))
            return null;

        try
        {
            return JsonDocument.Parse(json);
        }
        catch (JsonException)
        {
            return null;
        }
    }

    private static HashSet<string> ReadStringValues(JsonElement? parent, string propertyName, IEqualityComparer<string> comparer)
    {
        var values = new HashSet<string>(comparer);
        if (parent is not { ValueKind: JsonValueKind.Object } parentObject ||
            !parentObject.TryGetProperty(propertyName, out var property))
        {
            return values;
        }

        switch (property.ValueKind)
        {
            case JsonValueKind.Array:
                foreach (var item in property.EnumerateArray())
                {
                    var value = item.GetString();
                    if (!string.IsNullOrWhiteSpace(value))
                        values.Add(value);
                }
                break;
            case JsonValueKind.String:
                var single = property.GetString();
                if (!string.IsNullOrWhiteSpace(single))
                    values.Add(single);
                break;
        }

        return values;
    }

    private static void WriteStringArray(Utf8JsonWriter writer, string propertyName, IEnumerable<string> values)
    {
        writer.WritePropertyName(propertyName);
        writer.WriteStartArray();
        foreach (var value in values)
            writer.WriteStringValue(value);
        writer.WriteEndArray();
    }

    private static string EscapeYamlScalar(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string EscapeSingleQuotedScalar(string value) =>
        value.Replace("'", "''", StringComparison.Ordinal);

    private static string EscapeTomlString(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static bool IsWithin(string path, string root)
    {
        var normalizedPath = path.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var normalizedRoot = root.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);

        if (normalizedPath.Equals(normalizedRoot, StringComparison.OrdinalIgnoreCase))
            return true;

        var prefix = normalizedRoot + Path.DirectorySeparatorChar;
        return normalizedPath.StartsWith(prefix, StringComparison.OrdinalIgnoreCase);
    }

    private static bool PathsEqual(string left, string right) =>
        Path.GetFullPath(left).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            .Equals(
                Path.GetFullPath(right).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar),
                StringComparison.OrdinalIgnoreCase);

    private static void DeleteParentDirectoryIfEmpty(string filePath)
    {
        var parent = Path.GetDirectoryName(filePath);
        if (string.IsNullOrEmpty(parent) || !Directory.Exists(parent))
            return;

        if (!Directory.EnumerateFileSystemEntries(parent).Any())
            Directory.Delete(parent);
    }

    private static string GetArtifactDescription(string projectRoot, ArtifactKind kind, string artifactName)
    {
        var artifactDir = Path.Combine(projectRoot, ".lorex", kind.FolderName(), artifactName);
        var entryPath = ArtifactFileConvention.ResolveEntryPath(kind, artifactDir);
        if (entryPath is not null)
        {
            try
            {
                var yaml = SimpleYamlParser.ExtractFrontmatterYaml(File.ReadAllText(entryPath));
                if (yaml is not null)
                {
                    var dict = SimpleYamlParser.ParseToDictionary(yaml);
                    if (dict.TryGetValue("description", out var description))
                        return description;
                }
            }
            catch
            {
            }
        }

        if (kind == ArtifactKind.Skill)
        {
            var metadataPath = Path.Combine(artifactDir, "metadata.yaml");
            if (File.Exists(metadataPath))
            {
                try
                {
                    var dict = SimpleYamlParser.ParseToDictionary(File.ReadAllText(metadataPath));
                    if (dict.TryGetValue("description", out var description))
                        return description;
                }
                catch
                {
                }
            }
        }

        return artifactName;
    }

    private static string GetArtifactBody(string projectRoot, ArtifactKind kind, string artifactName)
    {
        var artifactDir = Path.Combine(projectRoot, ".lorex", kind.FolderName(), artifactName);
        var entryPath = ArtifactFileConvention.ResolveEntryPath(kind, artifactDir)
            ?? throw new InvalidOperationException($"{kind.Title()} '{artifactName}' is missing {kind.CanonicalFileName()}.");

        return ArtifactFileConvention.ExtractBody(File.ReadAllText(entryPath));
    }
}
